"""Tranche-2 acceptance: problem-set answer keys 1-4 reproduce in declarepy.

Each problem set's computational chain is rebuilt with declarepy and compared
against fresh R reference runs (validation/reference/rgen_ps1_4.json,
generated by validation/r_scripts/ps_reference.R with the keys' own code)
and the keys' published decisions:

  PS1  power of a 100-unit two-arm trial; MDE = 0.6; N = 400 for ees 0.3
  PS2  covariate adjustment on lapop_brazil; power 0.737/0.583; N to 80%
  PS3  interaction (difference-in-CATEs) power; N > 3000 for 80%
  PS4  logit coef vs OLS vs logit-AME: bias/RMSE diagnosis

Tolerances follow VALIDATION_REPORT.md (power ±0.05, coverage ±0.03,
RMSE ±10%, bias ±0.02·sd(Y) — adapted to ±0.10 absolute for the logit
log-odds row, which lives on a different scale).

Usage: .venv/bin/python validation/validate_t2.py [--sims 2000] [--seed 464]
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np
import pandas as pd

import declarepy as dp

HERE = Path(__file__).parent
results: list[dict[str, object]] = []


def check(element: str, name: str, ours: float, ref: float, tol: float, kind: str = "abs") -> None:
    delta = float(ours) - float(ref)
    ok = abs(delta) <= (abs(tol * ref) if kind == "rel" else tol)
    results.append(
        {
            "element": element, "diagnosand": name,
            "python": round(float(ours), 5), "reference": round(float(ref), 5),
            "delta": round(delta, 5),
            "band": f"±{tol:.0%} rel" if kind == "rel" else f"±{tol:.4g}",
            "pass": ok,
        }
    )


def decide(element: str, name: str, ours: object, ref: object) -> None:
    results.append(
        {
            "element": element, "diagnosand": name,
            "python": ours, "reference": ref, "delta": "",
            "band": "same decision", "pass": ours == ref,
        }
    )


# ---------------------------------------------------------------- PS1
def ps1_design(N: int = 100, expected_effect_size: float = 0.1) -> dp.Design:
    ees = expected_effect_size
    return dp.Design(
        dp.Model(n=N, build=lambda n, rng: {"U": rng.normal(size=n)}),
        dp.potential_outcomes(lambda df, z, rng: ees * float(z) + df["U"].to_numpy()),
        dp.Inquiry("ATE", lambda df: float((df["Y1"] - df["Y0"]).mean())),
        dp.Assignment.simple(prob=0.5),
        dp.reveal_outcomes(),
        dp.Estimator.difference_in_means(inquiry="ATE"),
    )


def run_ps1(ref: dict, sims: int, seed: int) -> None:
    base = dp.diagnose(ps1_design(), sims=sims, seed=seed).diagnosands.iloc[0]
    check("PS1 base design", "power", base["power"], ref["ps1_power_base"][0]["power"], 0.05)

    grid = dp.redesign(ps1_design, expected_effect_size=[round(x, 1) for x in np.arange(0.1, 1.01, 0.1)])
    diag = dp.diagnose_all(grid, sims=sims, seed=seed).diagnosands
    for row in ref["ps1_mde"]:
        ees = float(row["expected_effect_size"])
        mine = diag[np.isclose(diag["expected_effect_size"].astype(float), ees)].iloc[0]
        check(f"PS1 ees={ees}", "power", mine["power"], row["power"], 0.05)
    mde_mine = float(diag.loc[diag["power"] >= 0.8, "expected_effect_size"].astype(float).min())
    decide("PS1", "minimum detectable effect (answer: 0.6)", mde_mine, 0.6)

    bonus = dp.redesign(lambda N: ps1_design(N=N, expected_effect_size=0.3), N=list(range(100, 501, 100)))
    bdiag = dp.diagnose_all(bonus, sims=sims, seed=seed).diagnosands
    for row in ref["ps1_bonus"]:
        mine = bdiag[bdiag["N"] == int(row["N"])].iloc[0]
        check(f"PS1 bonus N={row['N']}", "power", mine["power"], row["power"], 0.05)
    n_mine = int(bdiag.loc[bdiag["power"] >= 0.8, "N"].min())
    decide("PS1 bonus", "smallest N with 80% power at ees=0.3 (answer: 400)", n_mine, 400)


# ---------------------------------------------------------------- PS2
PS2_COVARS = "govt_pride + trust_military + trust_supreme_court + support_political_system"


def make_ps2_design(lapop: pd.DataFrame) -> "callable":
    def factory(N: int = 1000) -> dp.Design:
        def po(df: pd.DataFrame, z: object, rng: np.random.Generator) -> np.ndarray:
            bump = rng.binomial(1, 0.35, len(df)) * float(z)
            return np.minimum(7, df["trust_police"].to_numpy() + bump)

        return dp.Design(
            dp.Model.resample(lapop, n=N),
            dp.potential_outcomes(po),
            dp.Inquiry("ATE", lambda df: float((df["Y1"] - df["Y0"]).mean())),
            dp.Assignment.simple(prob=0.5),
            dp.reveal_outcomes(),
            dp.Estimator.lm_robust("Y ~ Z", inquiry="ATE", label="unadjusted"),
            dp.Estimator.lm_robust(f"Y ~ Z + {PS2_COVARS}", inquiry="ATE", label="adjusted"),
        )

    return factory


def run_ps2(ref: dict, sims: int, seed: int) -> None:
    lapop = dp.data.load("lapop_brazil")
    factory = make_ps2_design(lapop)
    design = factory(1000)

    # Known-truth: ATE = 0.35 · P(trust_police < 7) analytically.
    analytic = 0.35 * float((lapop["trust_police"] < 7).mean())
    diag = dp.diagnose(design, sims=sims, seed=seed).diagnosands
    check("PS2", "mean estimand vs analytic truth", float(diag["mean_estimand"].iloc[0]), analytic, 0.01)
    # The key's single-draw estimand (0.274 in our R run; '0.266' in the text).
    check("PS2", "estimand (single R draw, wide band)", float(diag["mean_estimand"].iloc[0]),
          float(ref["ps2_estimand"][0]), 0.05)

    # R² of the covariate regression on one drawn dataset.
    dat = dp.draw_data(design, rng=seed)
    fit = dp.lm_robust(f"Y ~ {PS2_COVARS}", dat)
    check("PS2", "R² of covariate regression", float(fit.attrs["r_squared"]),
          float(ref["ps2_r_squared"][0]), 0.03)

    for row in ref["ps2_power_1000"]:
        mine = diag[diag["estimator"] == row["estimator"]].iloc[0]
        check(f"PS2 N=1000 {row['estimator']}", "power", mine["power"], row["power"], 0.05)

    grid = dp.redesign(factory, N=[1000, 1500, 2000, 2500, 3000])
    gdiag = dp.diagnose_all(grid, sims=sims, seed=seed).diagnosands
    for row in ref["ps2_power_grid"]:
        mine = gdiag[(gdiag["N"] == int(row["N"])) & (gdiag["estimator"] == row["estimator"])].iloc[0]
        check(f"PS2 N={row['N']} {row['estimator']}", "power", mine["power"], row["power"], 0.05)
    for est in ["adjusted", "unadjusted"]:
        sub_r = pd.DataFrame([r for r in ref["ps2_power_grid"] if r["estimator"] == est])
        sub_m = gdiag[gdiag["estimator"] == est]
        n_r = int(sub_r.loc[sub_r["power"] >= 0.8, "N"].min())
        n_m = int(sub_m.loc[sub_m["power"] >= 0.8, "N"].min())
        decide("PS2", f"smallest grid N reaching 80% power ({est})", n_m, n_r)


# ---------------------------------------------------------------- PS3
def ps3_design(N: int = 100) -> dp.Design:
    def po(df: pd.DataFrame, z: object, rng: np.random.Generator) -> np.ndarray:
        x = df["X"].to_numpy()
        p = 0.3 + 0.1 * x + 0.1 * float(z) + 0.1 * x * float(z)
        return rng.binomial(1, p)

    return dp.Design(
        dp.Model(n=N, build=lambda n, rng: {"X": rng.binomial(1, 0.5, n)}),
        dp.potential_outcomes(po),
        dp.Assignment.complete(prob=0.5),
        dp.reveal_outcomes(),
        dp.Estimator.lm_robust("Y ~ X + Z + X:Z", term="X:Z"),
    )


def run_ps3(ref: dict, sims: int, seed: int) -> None:
    base = dp.diagnose(ps3_design(), sims=sims, seed=seed).diagnosands.iloc[0]
    check("PS3 N=100", "power", base["power"], ref["ps3_power_100"][0]["power"], 0.05)
    grid = dp.redesign(ps3_design, N=[100, 500, 1000, 3000, 5000])
    diag = dp.diagnose_all(grid, sims=sims, seed=seed).diagnosands
    for row in ref["ps3_power_grid"]:
        mine = diag[diag["N"] == int(row["N"])].iloc[0]
        check(f"PS3 N={row['N']}", "power", mine["power"], row["power"], 0.05)
    # The reference power at N=3000 is 0.802 — exactly on the 80% threshold —
    # so the crossing N is a knife-edge decision; accept 3000 or 5000 as the
    # same substantive answer ("N must be ~3000 or larger").
    n_mine = int(diag.loc[diag["power"] >= 0.8, "N"].min())
    decide("PS3", "80% power crossing at N≈3000 (knife-edge: 3000 or 5000)", n_mine in (3000, 5000), True)


# ---------------------------------------------------------------- PS4
def ps4_design() -> dp.Design:
    def po(df: pd.DataFrame, z: object, rng: np.random.Generator) -> np.ndarray:
        return (0.1 * float(z) + df["U"].to_numpy() > 0.8).astype(float)

    return dp.Design(
        dp.Model(n=100, build=lambda n, rng: {"U": rng.uniform(size=n), "X": rng.normal(size=n)}),
        dp.potential_outcomes(po),
        dp.Inquiry("ATE", lambda df: float((df["Y1"] - df["Y0"]).mean())),
        dp.Assignment.complete(prob=0.5),
        dp.reveal_outcomes(),
        dp.Estimator.lm_robust("Y ~ Z + X", se_type="classical", term="Z", inquiry="ATE", label="ols"),
        dp.Estimator.logit("Y ~ Z + X", term="Z", inquiry="ATE", label="logit"),
        dp.Estimator.logit_ame("Y ~ Z + X", term="Z", inquiry="ATE", label="logit-marginal-effect"),
    )


def run_ps4(ref: dict, sims: int, seed: int) -> None:
    diag = dp.diagnose(ps4_design(), sims=sims, seed=seed).diagnosands
    sd_y = float(dp.draw_data(ps4_design(), rng=1)["Y"].std(ddof=1))
    for row in ref["ps4_diagnosis"]:
        est = row["estimator"]
        mine = diag[diag["estimator"] == est].iloc[0]
        bias_band = 0.10 if est == "logit" else max(0.02 * sd_y, 0.01)
        check(f"PS4 {est}", "bias", mine["bias"], row["bias"], bias_band)
        check(f"PS4 {est}", "rmse", mine["rmse"], row["rmse"], 0.10, "rel")
        check(f"PS4 {est}", "power", mine["power"], row["power"], 0.05)
        check(f"PS4 {est}", "coverage", mine["coverage"], row["coverage"], 0.03)
    # The key's decision: OLS and the AME are essentially identical; logit coef biased.
    b = {r["estimator"]: abs(float(diag.loc[diag["estimator"] == r["estimator"], "bias"].iloc[0]))
         for r in ref["ps4_diagnosis"]}
    decide("PS4", "logit coef biased; ols & AME unbiased",
           b["logit"] > 0.3 and b["ols"] < 0.02 and b["logit-marginal-effect"] < 0.02, True)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--sims", type=int, default=2000)
    ap.add_argument("--seed", type=int, default=464)
    args = ap.parse_args()

    with open(HERE / "reference" / "rgen_ps1_4.json") as f:
        ref = json.load(f)

    run_ps1(ref, args.sims, args.seed)
    print("PS1 done")
    run_ps2(ref, args.sims, args.seed)
    print("PS2 done")
    run_ps3(ref, args.sims, args.seed)
    print("PS3 done")
    run_ps4(ref, args.sims, args.seed)
    print("PS4 done")

    table = pd.DataFrame(results)
    pd.set_option("display.width", 160)
    print(table.to_string(index=False))
    n_fail = int((~table["pass"].astype(bool)).sum())
    print(f"\n{len(table)} checks, {n_fail} failures (sims={args.sims}, seed={args.seed})")
    table.to_csv(HERE / "t2_results.csv", index=False)
    print(f"written {HERE / 't2_results.csv'}")
    return 1 if n_fail else 0


if __name__ == "__main__":
    raise SystemExit(main())
