"""Tranche-3 ch15 acceptance: observational descriptive designs.

Validates the declarepy translations of declarations 15.1-15.6 against the
book's saved diagnosis objects where those are reproducible, and against
fresh R references (generated by validation/r_scripts/t3_ch15_reference.R)
where the book drew its fixed population with no seed:

  declaration_15.1  diagnosis_15.1.json      (book; custom bias/rmse)
  declaration_15.2  diagnosis_15.2.json      (book; effort sweep 0..5)
  declaration_15.3  rgen_t3_ch15_15_3.json   (fresh; cluster_prob 0.1..0.9)
  declaration_15.5  rgen_t3_ch15_15_4.json   (fresh; 3 estimators, incl 15.4's)
  declaration_15.6  diagnosis_15.5.json      (book; grouped by outcome)

The book's diagnosis_15.1/15.2 are directly usable because declaration_15.1.R
itself fixes ``set.seed(343)`` — the exported ch15_portola.csv reproduces the
book's population estimand 4.2919047619 exactly (asserted here and in the R
script). Fit-level checks (rgen_t3_ch15_fitchecks.json) pin the private
helpers to R on one fixed dataset: princomp first scores (both correlation
signs, exact), lm-based post-stratification (exact), and the Laplace GLMM vs
lme4::glmer (small numeric band).

For 15.4/15.5, DeclareDesign pools 50 per-state estimate rows into a single
diagnosand row per estimator; declarepy's per-state inquiries produce 50
groups, so this script recomputes the pooled diagnosands from the raw
simulations frame with DeclareDesign's own formulas.

Tolerances follow VALIDATION_REPORT.md: bias/mean_estimate/mean_estimand
±0.02·sd(Y), power ±0.05, coverage ±0.03, sd_estimate/rmse ±10% relative.
Deterministic quantities (fixed-population estimands) get near-exact bands.

Usage:  .venv/bin/python validation/validate_t3_ch15.py [--sims 2000] [--seed 464]
"""

from __future__ import annotations

import argparse
import json
import warnings
from pathlib import Path
from typing import Optional

import numpy as np
import pandas as pd

# Intercept-only fits on a constant outcome (e.g. "R ~ 1" when everyone
# responds at high effort) make statsmodels' r² divide by zero; the SEs and
# estimates declarepy consumes are unaffected (R's lm_robust prints NaN r²
# there too).
warnings.filterwarnings(
    "ignore",
    message="divide by zero encountered in scalar divide",
    category=RuntimeWarning,
    module="statsmodels",
)

import declarepy as dp
from declarepy.library.ch15 import (
    _fit_full_pooling,
    _fit_no_pooling,
    _fit_partial_pooling,
    _load,
    _princomp_first_score,
    _r_cut,
    declaration_15_1,
    declaration_15_2,
    declaration_15_3,
    declaration_15_5,
    declaration_15_6,
)

HERE = Path(__file__).parent
REF = HERE / "reference"

results: list[dict[str, object]] = []


def load_ref(name: str) -> dict:
    with open(REF / f"{name}.json") as f:
        return json.load(f)


def check(
    element: str,
    diagnosand: str,
    ours: float,
    ref: Optional[float],
    tol: float,
    kind: str = "abs",
) -> None:
    if ref is None or (isinstance(ref, float) and np.isnan(ref)):
        return
    delta = float(ours) - float(ref)
    if kind == "rel":
        ok = abs(delta) <= abs(tol * ref)
        band = f"±{tol:.0%} rel"
    else:
        ok = abs(delta) <= tol
        band = f"±{tol:.4g}"
    results.append(
        {
            "element": element,
            "diagnosand": diagnosand,
            "python": round(float(ours), 6),
            "reference": round(float(ref), 6),
            "delta": round(delta, 6),
            "band": band,
            "pass": ok,
        }
    )


def check_fit(element: str, name: str, max_abs_diff: float, tol: float) -> None:
    """Fit-level check row: max |python − R| on one fixed dataset."""
    results.append(
        {
            "element": element,
            "diagnosand": name,
            "python": float(f"{max_abs_diff:.3g}"),
            "reference": 0.0,
            "delta": float(f"{max_abs_diff:.3g}"),
            "band": f"≤{tol:g}",
            "pass": max_abs_diff <= tol,
        }
    )


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--sims", type=int, default=2000)
    ap.add_argument("--seed", type=int, default=464)
    args = ap.parse_args()
    sims, seed = args.sims, args.seed

    # ---- fit-level helper checks (fixed datasets, no Monte Carlo) ---------
    fc = load_ref("rgen_t3_ch15_fitchecks")
    for key, label in (("princomp_pos", "r>0"), ("princomp_neg", "r<0")):
        o = fc[key]
        py = _princomp_first_score(np.asarray(o["Y_1"]), np.asarray(o["Y_2"]))
        check_fit(f"helper princomp ({label})", "max|score-R|", float(np.max(np.abs(py - np.asarray(o["scores"])))), 1e-9)
    g = fc["glmm"]
    gdf = pd.DataFrame(
        {
            "policy_support": g["policy_support"],
            "HS": g["HS"],
            "state": g["state"],
            "PS_weight": g["PS_weight"],
        }
    )
    for fn, ref_key, label, tol in (
        (_fit_partial_pooling, "est_partial", "glmm partial pooling", 2e-3),
        (_fit_no_pooling, "est_no_pooling", "ols no pooling", 1e-8),
        (_fit_full_pooling, "est_full_pooling", "ols full pooling", 1e-8),
    ):
        est = fn(gdf)
        assert list(est["state"]) == g["states_sorted"]
        diff = float(np.max(np.abs(est["estimate"].to_numpy() - np.asarray(g[ref_key]))))
        check_fit(f"helper {label}", "max|estimate-R|", diff, tol)

    # ---- declaration_15.1: custom bias/rmse diagnosands -------------------
    portola_y = _r_cut(_load("ch15_portola")["Y_star"].to_numpy(), 7)
    assert abs(float(portola_y.mean()) - 4.2919047619) < 1e-9
    sd_y1 = float(np.std(portola_y, ddof=1))
    ref1 = load_ref("diagnosis_15.1")["diagnosands"][0]
    dgs_15_1 = dp.Diagnosands(
        bias=lambda d: float((d["estimate"] - d["estimand"]).mean()),
        rmse=lambda d: float(np.sqrt(((d["estimate"] - d["estimand"]) ** 2).mean())),
    )
    diag1 = dp.diagnose(declaration_15_1(), sims=sims, seed=seed, diagnosands=dgs_15_1).diagnosands.iloc[0]
    check("declaration_15.1", "bias", diag1["bias"], ref1["bias"], 0.02 * sd_y1)
    check("declaration_15.1", "rmse", diag1["rmse"], ref1["rmse"], 0.10, "rel")

    # ---- declaration_15.2: effort sweep, mean + response-rate estimators --
    ref2 = load_ref("diagnosis_15.2")["diagnosands"]
    efforts = sorted({float(r["effort"]) for r in ref2})
    grid2 = dp.redesign(declaration_15_2, effort=efforts)
    diag2 = dp.diagnose_all(grid2, sims=sims, seed=seed).diagnosands
    for row in ref2:
        eff = float(row["effort"])
        est_label = str(row["estimator"])
        mine = diag2[
            np.isclose(diag2["effort"].astype(float), eff)
            & (diag2["estimator"] == est_label)
        ].iloc[0]
        el = f"declaration_15.2 effort={eff} {est_label}"
        if est_label == "estimator":  # mean of responders, inquiry Y_bar
            check(el, "mean_estimand", mine["mean_estimand"], row["mean_estimand"], 1e-6)
            check(el, "mean_estimate", mine["mean_estimate"], row["mean_estimate"], 0.02 * sd_y1)
            check(el, "bias", mine["bias"], row["bias"], 0.02 * sd_y1)
            check(el, "sd_estimate", mine["sd_estimate"], row["sd_estimate"], 0.10, "rel")
            check(el, "rmse", mine["rmse"], row["rmse"], 0.10, "rel")
            check(el, "power", mine["power"], row["power"], 0.05)
            check(el, "coverage", mine["coverage"], row["coverage"], 0.03)
        else:  # Response Rate: no inquiry; R is a 0/1 share (sd ≈ 0.5)
            check(el, "mean_estimate", mine["mean_estimate"], row["mean_estimate"], 0.01)
            check(el, "sd_estimate", mine["sd_estimate"], row["sd_estimate"], 0.10, "rel")
            check(el, "power", mine["power"], row["power"], 0.05)

    # ---- declaration_15.3: cluster_prob sweep (fresh R reference) ---------
    nigeria_y = _r_cut(_load("ch15_two_nigerian_states")["Y_star"].to_numpy(), 7)
    sd_y3 = float(np.std(nigeria_y, ddof=1))
    ref3 = load_ref("rgen_t3_ch15_15_3")["diagnosands"]
    probs = sorted({round(float(r["cluster_prob"]), 3) for r in ref3})
    grid3 = dp.redesign(declaration_15_3, cluster_prob=probs)
    diag3 = dp.diagnose_all(grid3, sims=sims, seed=seed).diagnosands
    for row in ref3:
        cp = round(float(row["cluster_prob"]), 3)
        mine = diag3[np.isclose(diag3["cluster_prob"].astype(float), cp)].iloc[0]
        el = f"declaration_15.3 cluster_prob={cp}"
        check(el, "mean_estimand", mine["mean_estimand"], row["mean_estimand"], 1e-9)
        check(el, "mean_estimate", mine["mean_estimate"], row["mean_estimate"], 0.02 * sd_y3)
        check(el, "bias", mine["bias"], row["bias"], 0.02 * sd_y3)
        check(el, "sd_estimate", mine["sd_estimate"], row["sd_estimate"], 0.10, "rel")
        check(el, "rmse", mine["rmse"], row["rmse"], 0.10, "rel")
        check(el, "power", mine["power"], row["power"], 0.05)
        check(el, "coverage", mine["coverage"], row["coverage"], 0.03)

    # ---- declaration_15.4/15.5: MRP, pooled across the 50 states ----------
    # DD reports one row per estimator over sims × 50 state rows; declarepy
    # diagnoses 50 per-state inquiry groups, so pool from the raw simulations
    # frame with DD's own formulas (policy_support is 0/1: 0.02·sd(Y) = 0.01).
    ref4 = {str(r["estimator"]): r for r in load_ref("rgen_t3_ch15_15_4")["diagnosands"]}
    sims4 = dp.diagnose(declaration_15_5(), sims=sims, seed=seed).simulations
    for est_label, d in sims4.groupby("estimator"):
        row4 = ref4[str(est_label)]
        el = f"declaration_15.5 {est_label}"
        check(el, "mean_estimand", float(d["estimand"].mean()), row4["mean_estimand"], 1e-9)
        check(el, "mean_estimate", float(d["estimate"].mean()), row4["mean_estimate"], 0.01)
        check(el, "bias", float((d["estimate"] - d["estimand"]).mean()), row4["bias"], 0.01)
        check(el, "sd_estimate", float(d["estimate"].std(ddof=1)), row4["sd_estimate"], 0.10, "rel")
        check(
            el,
            "rmse",
            float(np.sqrt(((d["estimate"] - d["estimand"]) ** 2).mean())),
            row4["rmse"],
            0.10,
            "rel",
        )

    # ---- declaration_15.6: index construction, grouped by outcome ---------
    ref6 = load_ref("diagnosis_15.5")["diagnosands"]
    diag6 = dp.diagnose(declaration_15_6(), sims=sims, seed=seed).diagnosands
    sample6 = dp.draw_data(declaration_15_6(), rng=1)
    for row in ref6:
        outcome = str(row["outcome"])
        mine = diag6[diag6["outcome"] == outcome].iloc[0]
        sd_out = float(sample6[outcome].std(ddof=1))
        el = f"declaration_15.6 {outcome}"
        check(el, "mean_estimand", mine["mean_estimand"], row["mean_estimand"], 0.02)
        check(el, "mean_estimate", mine["mean_estimate"], row["mean_estimate"], 0.02 * sd_out)
        check(el, "bias", mine["bias"], row["bias"], 0.02 * sd_out)
        check(el, "sd_estimate", mine["sd_estimate"], row["sd_estimate"], 0.10, "rel")
        check(el, "rmse", mine["rmse"], row["rmse"], 0.10, "rel")
        check(el, "power", mine["power"], row["power"], 0.05)
        check(el, "coverage", mine["coverage"], row["coverage"], 0.03)

    # ---- report -----------------------------------------------------------
    table = pd.DataFrame(results)
    pd.set_option("display.width", 160)
    print(table.to_string(index=False))
    n_fail = int((~table["pass"]).sum())
    print(f"\n{len(table)} checks, {n_fail} failures (sims={sims}, seed={seed})")
    out = HERE / "t3_results_ch15.csv"
    table.to_csv(out, index=False)
    print(f"written {out}")
    return 1 if n_fail else 0


if __name__ == "__main__":
    raise SystemExit(main())
