"""T3 acceptance, chapter 9: validate declarations 9.2 - 9.7.

Compares declarepy translations of declaration_9.2 ... declaration_9.7 against
the book's saved diagnosis objects (validation/reference/diagnosis_9.*.json)
under the VALIDATION_REPORT.md protocol:

    bias/mean_* ±0.02·sd(Y)   power ±0.05   coverage ±0.03
    rmse / sd_estimate ±10% relative

For the tiny-n designs (9.2, 9.3, 9.4 sample n=3) the mean_estimate/bias band
is ±0.05·sd(age), following validate_t1.py's documented precedent for
declaration 9.1: the per-side Monte-Carlo se of mean_estimate is
sd_estimate/sqrt(2000) ≈ 0.30, so a ±0.02·sd band (≈0.47) would reject a
correct translation ~25% of the time.

Also checks the chapter's private helpers against deterministic estimatr
references (validation/reference/rgen_t3_ch09_*.json, generated by
validation/r_scripts/t3_ch09_reference.R):

    _lh_robust_test       vs estimatr::lh_robust (declaration 9.2's test)
    _lm_robust_weighted   vs weighted lm_robust HC2 / clustered CR2 + BM df
                          (declarations 9.6 and 9.7), incl. the observed
                          Foos et al. estimate used by diagnosis_9.7.R

Usage:  .venv/bin/python validation/validate_t3_ch09.py [--sims 2000] [--seed 464]
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Optional

import numpy as np
import pandas as pd

import declarepy as dp
from declarepy.library.ch09 import (
    _lh_robust_test,
    _lm_robust_weighted,
    declaration_9_2,
    declaration_9_3,
    declaration_9_4,
    declaration_9_5,
    declaration_9_6,
    declaration_9_7,
)

HERE = Path(__file__).parent
REF = HERE / "reference"

results: list[dict[str, object]] = []

# Population sd of the designs' outcome scales (band units).
SD_AGE_9_123 = float(np.sqrt((81.0**2 - 1) / 12.0))  # ages ~ U{0..80}: 23.38
SD_AGE_9_4 = 23.0  # rnorm(N, true_mean, 23); rounding adds only var 1/12


def load_ref(name: str) -> dict:
    with open(REF / f"{name}.json") as f:
        return json.load(f)


def check(
    element: str,
    diagnosand: str,
    ours: float,
    ref: Optional[float],
    tol: float,
    kind: str = "abs",
) -> None:
    if ref is None or (isinstance(ref, float) and np.isnan(ref)):
        return
    delta = float(ours) - float(ref)
    if kind == "rel":
        ok = abs(delta) <= abs(tol * ref)
        band = f"±{tol:.0%} rel"
    else:
        ok = abs(delta) <= tol
        band = f"±{tol:.4g}"
    results.append(
        {
            "element": element,
            "diagnosand": diagnosand,
            "python": round(float(ours), 6),
            "reference": round(float(ref), 6),
            "delta": round(float(delta), 6),
            "band": band,
            "pass": ok,
        }
    )


R2PY = {
    "estimate": "estimate",
    "std.error": "std_error",
    "statistic": "statistic",
    "p.value": "p_value",
    "conf.low": "conf_low",
    "conf.high": "conf_high",
    "df": "df",
}


def check_tidy_row(element: str, mine: pd.Series, ref_row: dict) -> None:
    """Deterministic estimator parity: every inference column vs estimatr."""
    for rkey, pkey in R2PY.items():
        tol = 1e-6 if rkey == "df" else 1e-8
        check(element, pkey, float(mine[pkey]), float(ref_row[rkey]), tol)


def full_row_checks(
    element: str,
    mine: pd.Series,
    ref: dict,
    sd_scale: float,
    mean_band: float,
) -> None:
    """The seven default diagnosands of one reference row."""
    for key, tol, kind in [
        ("mean_estimand", 0.02 * sd_scale, "abs"),
        ("mean_estimate", mean_band * sd_scale, "abs"),
        ("bias", mean_band * sd_scale, "abs"),
        ("sd_estimate", 0.10, "rel"),
        ("rmse", 0.10, "rel"),
        ("power", 0.05, "abs"),
        ("coverage", 0.03, "abs"),
    ]:
        check(element, key, mine[key], ref.get(key), tol, kind)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--sims", type=int, default=2000)
    ap.add_argument("--seed", type=int, default=464)
    args = ap.parse_args()
    sims, seed = args.sims, args.seed

    # ---- helper parity: _lh_robust_test vs estimatr::lh_robust ---------
    lh = load_ref("rgen_t3_ch09_lh_robust")
    d2 = pd.DataFrame(lh["two_coef"]["data"])
    mine2 = _lh_robust_test("y ~ z", d2, lh["two_coef"]["linear_hypothesis"])
    ref_row2 = [r for r in lh["two_coef"]["tidy"] if r["term"] == "z = 0.5"][0]
    check_tidy_row("helper lh_robust (y ~ z, 'z = 0.5')", mine2.iloc[0], ref_row2)
    d1 = pd.DataFrame(lh["intercept_only"]["data"])
    mine1 = _lh_robust_test("age ~ 1", d1, lh["intercept_only"]["linear_hypothesis"])
    check_tidy_row(
        "helper lh_robust (age ~ 1, '(Intercept) = 20')",
        mine1.iloc[0],
        lh["intercept_only"]["row"],
    )

    # ---- helper parity: _lm_robust_weighted (HC2, CR2) -----------------
    for name, kwargs in [("wls_hc2", {}), ("wls_cr2", {"clusters": "cl"})]:
        ref_wls = load_ref(f"rgen_t3_ch09_{name}")
        dd = pd.DataFrame(ref_wls["data"])
        mine_wls = _lm_robust_weighted("y ~ z", dd, weights="w", term="all", **kwargs)
        for ref_row in ref_wls["tidy"]:
            term = "Intercept" if ref_row["term"] == "(Intercept)" else ref_row["term"]
            row = mine_wls[mine_wls["term"] == term].iloc[0]
            check_tidy_row(f"helper weighted lm_robust {name} [{ref_row['term']}]", row, ref_row)

    # ---- helper parity: the observed Foos et al. estimate (9.7) --------
    foos = dp.data.load("foos_etal")
    obs_tidy = _lm_robust_weighted(
        "marked_register_2014 ~ treat + ward", foos, weights="weights", clusters="street"
    )
    obs_row = obs_tidy.iloc[0]
    ref_obs = [
        r for r in load_ref("rgen_t3_ch09_foos_observed")["tidy"] if r["term"] == "treat"
    ][0]
    check_tidy_row("helper weighted CR2 foos observed [treat]", obs_row, ref_obs)
    observed_estimate = float(obs_row["estimate"])

    # ---- declaration_9.2: lm_robust row + lh_robust test row -----------
    ref92 = load_ref("diagnosis_9.2")["diagnosands"]
    diag92 = dp.diagnose(declaration_9_2(), sims=sims, seed=seed).diagnosands
    for ref in ref92:
        mine = diag92[diag92["estimator"] == ref["estimator"]].iloc[0]
        full_row_checks(
            f"declaration_9.2 [{ref['estimator']}]", mine, ref, SD_AGE_9_123, 0.05
        )

    # ---- declaration_9.3: Bayesian estimator (power/coverage NA) -------
    ref93 = load_ref("diagnosis_9.3")["diagnosands"][0]
    diag93 = dp.diagnose(declaration_9_3(), sims=sims, seed=seed).diagnosands.iloc[0]
    # power/coverage are null in the reference (no p-value/CI) -> skipped.
    full_row_checks("declaration_9.3", diag93, ref93, SD_AGE_9_123, 0.05)

    # ---- declaration_9.4: redesign over true_mean ----------------------
    ref94 = load_ref("diagnosis_9.4")["diagnosands"]
    grid94 = dp.redesign(declaration_9_4, true_mean=list(np.linspace(0.0, 100.0, 10)))
    diag94 = dp.diagnose_all(grid94, sims=sims, seed=seed).diagnosands
    for ref in ref94:
        tm = float(ref["true_mean"])
        mine = diag94[np.isclose(diag94["true_mean"].astype(float), tm)].iloc[0]
        full_row_checks(
            f"declaration_9.4 true_mean={tm:.1f}", mine, ref, SD_AGE_9_4, 0.05
        )

    # ---- declaration_9.5: bootstrap se of the Hajj DiM -----------------
    ref95 = load_ref("diagnosis_9.5")["data"][0]
    diag95 = dp.diagnose(declaration_9_5(), sims=sims, seed=seed).diagnosands.iloc[0]
    check("declaration_9.5", "sd_estimate", diag95["sd_estimate"], ref95["se"], 0.10, "rel")

    # ---- declaration_9.6: four design/answer-strategy combinations ----
    ref96 = load_ref("diagnosis_9.6")["diagnosands"]
    designs96 = declaration_9_6()
    diag96 = dp.diagnose_all(designs96, sims=sims, seed=seed).diagnosands
    # sd(Y) per design, pooled over 20 model draws (draw_data noise damping).
    for ref, design in zip(ref96, designs96):
        ys = np.concatenate(
            [dp.draw_data(design, rng=s)["Y"].to_numpy(dtype=float) for s in range(1, 21)]
        )
        sd_y = float(np.std(ys, ddof=1))
        mine = diag96[diag96["design"] == ref["design"]].iloc[0]
        assert mine["estimator"] == ref["estimator"], (mine["estimator"], ref["estimator"])
        full_row_checks(
            f"declaration_9.6 {ref['design']} [{ref['estimator']}]",
            mine,
            ref,
            sd_y,
            0.02,
        )

    # ---- declaration_9.7: randomization-inference p value --------------
    ref97 = load_ref("diagnosis_9.7")["diagnosands"][0]
    pv = dp.Diagnosands(
        p_value=lambda d: float((d["estimate"].abs() >= abs(observed_estimate)).mean())
    )
    diag97 = dp.diagnose(
        declaration_9_7(), sims=sims, seed=seed, diagnosands=pv
    ).diagnosands.iloc[0]
    check("declaration_9.7", "p.value", diag97["p_value"], ref97["p.value"], 0.05)

    # ---- report --------------------------------------------------------
    table = pd.DataFrame(results)
    pd.set_option("display.width", 170)
    print(table.to_string(index=False))
    n_fail = int((~table["pass"]).sum())
    print(f"\n{len(table)} checks, {n_fail} failures (sims={sims}, seed={seed})")
    out = HERE / "t3_results_ch09.csv"
    table.to_csv(out, index=False)
    print(f"written {out}")
    return 1 if n_fail else 0


if __name__ == "__main__":
    raise SystemExit(main())
